apiVersion: apps/v1
kind: Deployment

metadata:
  name: atlas-platform
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: atlas-platform
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi