apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pdb.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  managed-by: kustomize
  project: atlas-platform
